### ISSUE TITLE
Add missing `write` phase to the EI importing example

### ISSUE THREAD

**Issue by tngTUDOR** [brightway-lca/brightway-examples#7]
## Current

The [EI importing example](https://docs.brightway.dev/en/latest/content/examples/brightway-examples/data_import/ecoinvent_import.html) goes all the way to show a an importer without missing links, but does not include the `write` phase.

## Expected

The [example notebook](https://github.com/brightway-lca/brightway-examples/blob/main/data_import/ecoinvent_import.ipynb) includes the `write` phase.
This might be intended to be like so, to make the CI/CD flows work, but some more documentation should be added to make the reader aware of such, and provide the required instructions to actually write the db .

**Comment by cmutel** [comment]
Code path switch to use remote functionality
